# Generated by Django 5.0.4 on 2024-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_savingscalculator_potential_savings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingscalculator',
            name='user_savings_percent',
            field=models.FloatField(default=20.0),
        ),
    ]
